; L routes
RTE L23
	AWY
	FIX BINKA
		TO RTE M602
		TO RTE N746
		END
	FIX TORLO
		TO RTE P46
		TO RTE Z131
		END
	FIX UDAXI
		TO RTE M725
		END
	FIX FLD
		END
	FIX GEVNI
		TO RTE T239
		END
	FIX LEGSA
		TO RTE T206
		TO RTE T208
		END
	FIX TIMIB
		TO RTE Q280
		TO RTE M736
		END
	FIX KUBAB
		TO RTE P12
		END
	FIX NUVEN
		TO RTE M864
		END
	FIX TAGOB
		TO RTE M726
		END
	FIX BERIM
		END
	FIX RAMAR
		TO RTE T906
		TO RTE Z290
		END
	FIX HAM
		TO RTE M170
		TO RTE M852
		TO RTE P605
		END
	FIX ESTAD
		TO RTE N850
		END
	FIX STADE
		TO RTE M170
		TO RTE Y348
		END
	FIX WSN
		TO RTE N125
		TO RTE Y850
		TO RTE Z612
		TO RTE Z88
		END
	FIX GIBMA
		END
	END

 RTE L87
	AWY
	FIX XELOL
		DOWN
		END
	FIX PESEL
		DOWN
		END
	FIX RAKIT
		DOWN
		END
	FIX KETAP
		DOWN
		END
	FIX KUBOG
		DOWN
		END
	FIX VEVAS
		DOWN
		END
	FIX TADUV
		DOWN
		END
	FIX TOGRO
		DOWN
		END
	END

RTE L132
	AWY
	FIX MAH
		DOWN
		END
	FIX LASMI
		DOWN
		END
	FIX MAMOR
		DOWN
		TO RTE L610
		TO RTE Y104
		END
	FIX RUDNO
		DOWN
		TO RTE L604
		TO RTE M736
		END
	FIX AGNAV
		DOWN
		TO RTE P733
		END
	FIX BEKTO
		DOWN
		END
	FIX SUPIL
		DOWN
		END
	FIX KILNU
		DOWN
		END
	FIX ABKIS
		DOWN
		TO RTE Q240
		TO RTE Z715
		END
	FIX EPKEP
		DOWN
		TO RTE L620
		END
	FIX RIVSA
		DOWN
		TO RTE Z21
		END
	FIX OGSEN
		DOWN
		END
	FIX UNRIG
		DOWN
		END
	FIX PEPOL
		DOWN
		TO RTE N858
		END
	FIX SONUD
		DOWN
		TO RTE P203
		TO RTE Z20
		END
	FIX ANEBO
		DOWN
		END
	FIX RENKI
		DOWN
		TO RTE L619
		TO RTE M725
		TO RTE Y89
		END
	FIX BODLA
		DOWN
		TO RTE L733
		TO RTE Q316
		TO RTE Z717
		TO RTE Z491
		END
	FIX DEMUR
		DOWN
		TO RTE N146
		TO RTE Z491
		END
	END

RTE L173
	AWY
	FIX TITIG
		TO RTE Q112
		END
	FIX AMDID
		TO RTE N871
		TO RTE P994
		END
	FIX EBEDA
		TO RTE L603
		END
	FIX OTT
		TO RTE M867
		END
	FIX MAH
		DOWN
		TO RTE M726
		TO RTE Y100
		TO RTE Y109
		TO RTE L132
		END
	FIX LELTA
		DOWN
		TO RTE T107
		END
	FIX RIDAR
		DOWN
		TO RTE Z79
		TO RTE Z98
		END
	FIX DODIL
		DOWN
		TO RTE T127
		END
	FIX RIXED
		DOWN
		TO RTE Y191
		END
	FIX ABTAL
		END
		FIX GUPIN
		TO RTE Q863
		TO RTE N869
		TO RTE Z79
		END
	FIX LBU
		END
	END

RTE L179
	AWY
	FIX NIK
		END
	FIX SONDY
		END
	FIX ELSIK
		END
	FIX SORAT
		END
	FIX ROMUN
		END
	FIX DIBIR
		TO RTE T474
		TO RTE Z282
		END
	FIX VEBAK
		DOWN
		TO RTE Z334
		TO RTE Z283
		TO RTE Z850
		TO RTE T474
		END
	FIX ABODU
		DOWN
		END
	FIX SUMOP
		DOWN
		TO RTE Y869
		END
	FIX EKRUM
		DOWN
		END
	FIX LUSIX
		DOWN
		END
	FIX MEVEL
		DOWN
		TO RTE Z841
		TO RTE Z44
		TO RTE Y850
		END
	FIX MISRI
		DOWN
		TO RTE Z851
		END
	FIX OSN
		DOWN
		TO RTE Z718
		TO RTE M170
		END
	END
